### ISSUE TITLE
Weird indexing of person

### ISSUE THREAD

**Issue by xiaorui-ui** [AY2324S2-CS2103T-W13-1/tp#113]
![Screenshot 2024-04-03 164622](https://github.com/AY2324S2-CS2103T-W13-1/tp/assets/87259515/cdcd55a7-6137-477b-bb32-a51f71c6c6ae)

Irfan is person 5 in the main personList, but became effectively became person 1 after viewloan

**Comment by narwhalsilent** [comment]
Expected behaviour.
