### ISSUE TITLE
[PE-D][Tester C] Urgency Data when running analytics returns invalid percentage

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-1/tp#151]
![image.png](https://raw.githubusercontent.com/jovantanyk/ped/main/files/407cb052-9242-45c1-936d-c1e4a1896a46.png)
After adding a single loan with the start date 1900-01-01 and the return date 1990-01-02, the analytics command returns an urgency percentage in the negatives.

![image.png](https://raw.githubusercontent.com/jovantanyk/ped/main/files/58ea686e-c5b0-4075-985e-11346a703738.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: jovantanyk/ped#3

**Comment by marcus-ny** [comment]
Fixed by PR #201
