### ISSUE TITLE
[PE-D][Tester B] Find functionality does not cover partial search cases

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W13-1/tp#164]
The find command should ideally be able to find something with just a part of the word. For example, If I type in `find ale`, it should probably be able to find Alex Yeoh but instead, it says that there are 0 people listed. This is useful for cases when you do not remember the full attribute of the user like with a phone number or name or address. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: TarinPairor/ped#7

**Comment by marcus-ny** [comment]
Need to check original AB3 implementation. This was not changed in any way so this should be expected behaviour. Can be specified better in the UG.

**Comment by Joseph31416** [comment]
UG clearly stated that only full words will be matched.
